services:
  db:
    image: alpine:latest
    volumes:
      - ./.dep-health:/signal
    command: ["sh","-c","(sleep 1; echo ready >/signal/ready); while true; do sleep 1; done"]
    healthcheck:
      test: ["CMD", "test", "-f", "/signal/ready"]
      interval: 1s
      timeout: 1s
      retries: 10

  api:
    image: alpine:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.dep-health:/signal
    command: ["sh","-c","if test -f /signal/ready; then echo API_OK; tail -f /dev/null; else echo API_FAIL; exit 50; fi"]
